### ISSUE TITLE
IAsyncResult  vs SocketAsyncEventArgs

### ISSUE THREAD

**Issue by mmajcica** [ironyx/simplsockets#1]
Dear David,

I need to confess that this is the first time I laid my hands on Sockets. Previously I never had a need to use them. But I got quite interested in it so I spent some time learning. What I saw there are two approaches in making them work, via `IAsyncResult` as you did, or what should be a more performant way, via `SocketAsyncEventArgs`.
Is there a particular reason why you chose `IAsyncResult` instead of `SocketAsyncEventArgs`?
Would you consider passing on `SocketAsyncEventArgs` if I give a shot in implementing your contracts via `SocketAsyncEventArgs`?

Some interesting readings are the following:
http://msdn.microsoft.com/en-us/library/bb968780
http://www.codeproject.com/Articles/83102/C-SocketAsyncEventArgs-High-Performance-Socket-Cod?fid=1573061&select=4770014&fr=1#xx0xx
http://blogs.msdn.com/b/pfxteam/archive/2011/12/15/10248293.aspx

Cheers

**Comment by haneytron** [comment]
Mario,

Glad to see you're getting some socket experience. Very low-level and often fun stuff :)

In this case I chose `IAsyncResult` because it's a bit cleaner and more intuitive to use. You're correct in that `SocketAsyncEventArgs` in general (out of the box) are more performant than `IAsyncResult`. This is because `SocketAsyncEventArgs` use object pools (re-use of objects) to prevent creating and deleting state objects for each request. In my `IAsyncResult` implementation, I actually use object pools as well in other to avoid the performance issues. So, in short, it's true that `SocketAsyncEventArgs` might be a _tiny_ bit more performant than my implementation, but it's not necessary to switch it at this time because it is not a concern or bottleneck. If you can show me that it is substantially less performant, I'd happily accept the improved version using `SocketAsyncEventArgs`.

**Comment by mmajcica** [comment]
One thing is sure, we need to consider offering async methods for the operations. In this way it will be more in step with the times.

**Comment by haneytron** [comment]
Well, the asynchronous factor is intentionally handled by sharing a single connection and multiplexer. The multiplexer accomplishes the multi-threading efficiencies. We could make async/await that part of the code (the part where the code is waiting on the MUX signal to continue).

**Comment by haneytron** [comment]
Hi @mmajcica, long time no talk! ;)

I wanted to let you know that the latest version uses `SocketAsyncEventArgs` which does seem better. Cheers!

-Dave
